name: Deploy Production CD

on:
  release:
    types:
      - published
      - edited

jobs:
  deploy-production:
    name: Deploy to production server
    environment: production
    runs-on: ubuntu-latest

    steps:
      - name: Execute deployment command
        uses: appleboy/ssh-action@v1.0.3
        env:
          APP_PROD_PATH: ${{ vars.APP_PROD_PATH }}
          GIT_URL: ${{ secrets.GIT_URL }}
          MINIO_PROD_ENDPOINT: ${{ secrets.MINIO_PROD_ENDPOINT }}
          MINIO_PROD_ACCESS_KEY: ${{ secrets.MINIO_PROD_ACCESS_KEY }}
          MINIO_PROD_SECRET_KEY: ${{ secrets.MINIO_PROD_SECRET_KEY }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          APP_PROD_PORT_1: ${{ secrets.APP_PROD_PORT_1 }}
          APP_PROD_PORT_2: ${{ secrets.APP_PROD_PORT_2 }}
          APP_NAME: ${{ secrets.APP_IMAGE }}
          APP_TAG: ${{ github.event.release.tag_name }}

        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USER_NAME_PRODUCTION }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}
          envs: APP_PROD_PATH, GIT_URL, MINIO_PROD_ENDPOINT, MINIO_PROD_ACCESS_KEY, MINIO_PROD_SECRET_KEY, DOCKERHUB_USERNAME, DOCKERHUB_TOKEN, APP_PROD_PORT_1, APP_PROD_PORT_2, APP_NAME, APP_TAG
          script: |
            
            sudo docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN

            if [[ -d "${APP_PROD_PATH}" ]]; then 
              cd $APP_PROD_PATH
              sudo docker compose down
              git pull origin main
            else
              ssh-keyscan github.com > ~/.ssh/known_hosts
              git clone $GIT_URL $APP_PROD_PATH
              cd $APP_PROD_PATH
            fi

            # If there are any envars update
            echo "MINIO_PROD_ENDPOINT=$MINIO_PROD_ENDPOINT" > .env
            echo "MINIO_PROD_ACCESS_KEY=$MINIO_PROD_ACCESS_KEY" >> .env
            echo "MINIO_PROD_SECRET_KEY=$MINIO_PROD_SECRET_KEY" >> .env
            echo "APP_PROD_PORT_1=$APP_PROD_PORT_1" >> .env
            echo "APP_PROD_PORT_2=$APP_PROD_PORT_2" >> .env
            echo "APP_IMAGE=${APP_NAME}" >> .env
            echo "APP_TAG=$APP_TAG" >> .env

            # Run app
            sudo docker compose up pacmusic-prod-1 pacmusic-prod-2 --build --detach

      - name: Hit Endpoint
        run: |
          sleep 20
          curl ${{ secrets.PROD_URL }}